# Generated by Django 5.1.6 on 2025-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=120)),
                ('degree', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('start_date', models.CharField(max_length=120)),
                ('end_date', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('start_date', models.CharField(max_length=120)),
                ('end_date', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/projects')),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Both', 'Both')], max_length=50)),
                ('github_link', models.URLField()),
                ('project_link', models.URLField()),
                ('homepage_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images/skills')),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Both', 'Both'), ('None', 'None')], max_length=50)),
            ],
        ),
    ]
