# Generated by Django 5.0.6 on 2024-07-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='homepage_active',
            field=models.BooleanField(default=False),
        ),
    ]
