# Generated by Django 5.0.6 on 2024-07-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projectlist_homepage_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images/skills')),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science')], max_length=50)),
            ],
        ),
    ]
