# Generated by Django 5.0.6 on 2024-07-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skilllist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Both', 'Both')], max_length=50),
        ),
        migrations.AlterField(
            model_name='skilllist',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Both', 'Both')], max_length=50),
        ),
    ]
