# Generated by Django 5.0.6 on 2024-07-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_projectlist_category_alter_skilllist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllist',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Both', 'Both'), ('None', 'None')], max_length=50),
        ),
    ]
