# Generated by Django 5.0.6 on 2024-07-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_skilllist_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=120)),
                ('degree', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
